
    export const userData = [
        {
          name: 'Jan',
          "Active User": 4000,
        },
        {
            name: 'Feb',
            "Active User": 3000,
        },
        {
            name: 'Mar',
            "Active User": 1000,
        },
        {
          name: 'Apr',
          "Active User": 5000,
        },
        {
            name: 'May',
            "Active User": 2500,
        },
         {
          name: 'Jun',
          "Active User": 4500,
        },
        {
            name: 'Jul',
            "Active User": 3200,
        },
        {
            name: 'Aug',
            "Active User": 6000,
        },
        {
          name: 'Sep',
          "Active User": 1000,
        },
        {
            name: 'Oct',
            "Active User": 5000,
        },
        {
          name: 'Nov',
          "Active User": 3000,
        },
        {
            name: 'Dec',
            "Active User": 6969,
        },
      ];
      export const productData = [
        {
          name: 'Jan',
          "Sales": 3000,
        },
        {
            name: 'Feb',
            "Sales": 2000,
        },
        {
            name: 'Mar',
            "Sales": 5000,
        },
      ];

      export const userRows = [
        { id: 1, 
          userName: 'Beast',
          avatar:"https://lh3.googleusercontent.com/a-/AFdZucqZz-zwkbhZkGj-IQrleTi06ID5JgWBOHrJ0C-HGw=s576-p-no",
          email:"beast@coolmail.com",
          status:"active",
          transaction : "₹799",
        },
        { id: 2, 
          userName: 'Beast',
          avatar:"https://lh3.googleusercontent.com/a-/AFdZucqZz-zwkbhZkGj-IQrleTi06ID5JgWBOHrJ0C-HGw=s576-p-no",
          email:"beast@coolmail.com",
          status:"active",
          transaction : "₹799",
        },
        { id: 3, 
          userName: 'Beast',
          avatar:"https://lh3.googleusercontent.com/a-/AFdZucqZz-zwkbhZkGj-IQrleTi06ID5JgWBOHrJ0C-HGw=s576-p-no",
          email:"beast@coolmail.com",
          status:"active",
          transaction : "₹799",
        },
        { id: 4, 
          userName: 'Beast',
          avatar:"https://lh3.googleusercontent.com/a-/AFdZucqZz-zwkbhZkGj-IQrleTi06ID5JgWBOHrJ0C-HGw=s576-p-no",
          email:"beast@coolmail.com",
          status:"active",
          transaction : "₹799",
        },
        { id: 5, 
          userName: 'Beast',
          avatar:"https://lh3.googleusercontent.com/a-/AFdZucqZz-zwkbhZkGj-IQrleTi06ID5JgWBOHrJ0C-HGw=s576-p-no",
          email:"beast@coolmail.com",
          status:"active",
          transaction : "₹799",
        },
        { id: 6, 
          userName: 'Beast',
          avatar:"https://lh3.googleusercontent.com/a-/AFdZucqZz-zwkbhZkGj-IQrleTi06ID5JgWBOHrJ0C-HGw=s576-p-no",
          email:"beast@coolmail.com",
          status:"active",
          transaction : "₹799",
        },
        { id: 7, 
          userName: 'Beast',
          avatar:"https://lh3.googleusercontent.com/a-/AFdZucqZz-zwkbhZkGj-IQrleTi06ID5JgWBOHrJ0C-HGw=s576-p-no",
          email:"beast@coolmail.com",
          status:"active",
          transaction : "₹799",
        },
      ];
      
      export const productRows = [
        { id: 1, 
          name: 'Apple Airpods',
          img:"https://www.apple.com/v/airpods/r/images/overview/airpods_pro_right__fm0wwisa76em_large_2x.png",
          stock:69,
          status:"active",
          price : "₹24,999",
        },
        { id: 2, 
          name: 'Apple Airpods',
          img:"https://www.apple.com/v/airpods/r/images/overview/airpods_pro_right__fm0wwisa76em_large_2x.png",
          stock:69,
          status:"active",
          price : "₹24,999",
        },
        { id: 3, 
          name: 'Apple Airpods',
          img:"https://www.apple.com/v/airpods/r/images/overview/airpods_pro_right__fm0wwisa76em_large_2x.png",
          stock:69,
          status:"active",
          price : "₹24,999",
        },
        { id: 4, 
          name: 'Apple Airpods',
          img:"https://www.apple.com/v/airpods/r/images/overview/airpods_pro_right__fm0wwisa76em_large_2x.png",
          stock:69,
          status:"active",
          price : "₹24,999",
        },
        { id: 5, 
          name: 'Apple Airpods',
          img:"https://www.apple.com/v/airpods/r/images/overview/airpods_pro_right__fm0wwisa76em_large_2x.png",
          stock:69,
          status:"active",
          price : "₹24,999",
        },
        { id: 6, 
          name: 'Apple Airpods',
          img:"https://www.apple.com/v/airpods/r/images/overview/airpods_pro_right__fm0wwisa76em_large_2x.png",
          stock:69,
          status:"active",
          price : "₹24,999",
        },
        { id: 7, 
          name: 'Apple Airpods',
          img:"https://www.apple.com/v/airpods/r/images/overview/airpods_pro_right__fm0wwisa76em_large_2x.png",
          stock:69,
          status:"active",
          price : "₹24,999",
        },
      ];